# Generated by Django 3.2.23 on 2023-11-10 17:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geonode_mapstore_client', '0002_migrate_map_blob'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=250, verbose_name='displayName')),
                ('priority', models.IntegerField(default=3, verbose_name='priority')),
                ('url', models.CharField(default="{state('settings') && state('settings').geoserverUrl ? state('settings').geoserverUrl + '/wfs' : '/geoserver/wfs'}", max_length=250, verbose_name='URL of the WFS service')),
                ('typename', models.CharField(help_text='Geonode alternate', max_length=250, verbose_name='Typename')),
                ('attributes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), help_text='Comma separated list of attributes. Search is performed on these fields. Only textual fields can be configured.', max_length=250, size=None, verbose_name='attributes')),
                ('sortby', models.CharField(help_text='Sorting attribute, must be a dataset attribute', max_length=250, verbose_name='sortby')),
                ('srsName', models.CharField(default='EPSG:4326',help_text='ESPG:xxxx code of the CRS of returned geometries', max_length=250, verbose_name='srsName')),
                ('maxFeatures', models.IntegerField(default=20, help_text='Max features returned by the search', verbose_name='srsName')),
            ],
            options={
                'verbose_name': 'Search Service',
                'verbose_name_plural': 's',
            },
        ),
    ]
